### PR TITLE
Added html format

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by dimapaloskin** [comment]
Hello, @danielgindi.
Thanks for the your pull request.

It's should works as a basic support of the html files but there are few tricky parts. For example html file can starts with "<!doctype html>". So we need more complicated comparing. With current signature format it will very uncomfortably so I have a plans to implement regexp support for signatures. 

But yep, your code works for some cases and it's the reason why it merged =)

**Comment by danielgindi** [comment]
Well, I've thought about "<!doctype html>'", but that's a declaration for the beginning of the file.
But if the first bytes of the file contains `<html`, it is an HTML anyway.
It's like the SVG thing - the file _could_ begin with an XML declaration, but you search for `<svg` in the first bytes and so you match all cases.

We could add an `OR` rule for "contains `<!DOCTYPE html`", but I think that will be redundant.
The reason I also say "contains" and not "starts with", is that the doctype could also not be the first thing.
See this: https://www.w3.org/TR/xhtml11/conformance.html
The sample is:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html version="-//W3C//DTD XHTML 1.1//EN"
      xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.w3.org/1999/xhtml
                          http://www.w3.org/MarkUp/SCHEMA/xhtml11.xsd"
>
  <head>
    <title>Virtual Library</title>
  </head>
  <body>
    <p>Moved to <a href="http://example.org/">example.org</a>.</p>
  </body>
</html>
```

Anyway, as you can see I've added a UTF16 (aka. Microsoft Wide Character) version, as I've encountered such documents out there, which have been generated by microsoft tools.

**Comment by dimapaloskin** [comment]
Yes, you are right. I mentioned "doctype" just as example.

Html is not a binary format and using signatures quite difficult but yep, we need to detect basic cases via signatures!

I did add `addCustomFunction` method and update readme (also npm package) for complicated cases like html. Of course it goes against the main idea but that is easy way for other guys to add custom type checkers. 

Anyway, it's can be helpful for the detecting specific file types.
And thanks for the your PRs again :)

**Comment by danielgindi** [comment]
You're welcome :-) Thanks for this module!

**Pull request merged**
