### PR TITLE
Sorted out all common mpeg based video formats

### PR DESCRIPTION
**Pull request by danielgindi**
And some improvements to MOV and MP4 signatures

### CODE REVIEW

**Comment by danielgindi** [comment]
@dimapaloskin Have you had a chance to look at this?

**Comment by dimapaloskin** [comment]
Hello!

Could you add tests for your changes?
I can see that you comment mp4 test. It means that currently mp4 detecting broken?

**Comment by danielgindi** [comment]
Yes, the current mp4 detection is broken, as it does not distinguish between other formats, and the existing mp4 sample is m4v. 
Sadly I don't have a short sample that can be used for testing (I tested locally on big movie clips)

**Comment by dimapaloskin** [comment]
As I know mp4 just a container.
So is there any chance to put mp4 detecting after m4v?
In this case if `m4v` condition will not detect m4v format, `mp4` checking can affirm that file at least a mp4 container.

Specifically I'm don't think that refusing mp4 detecting is a good idea 🤔

**Comment by danielgindi** [comment]
You're correct, and we're not refusing anything.
It's detecting first the "more specific" mp4 containers, that belong to m4v, m4a, mov etc., and then tries to match against the more generic mp4.

It's just the unit test that if faulty

**Comment by dimapaloskin** [comment]
Ok, I will see soon (I guess tomorrow) what we can do with it :)

**Comment by danielgindi** [comment]
@dimapaloskin Any news on this?

**Comment by danielgindi** [comment]
@dimapaloskin I sorted out all the mpeg issues, now it's much more reliable and detects more formats more accurately

**Comment by dimapaloskin** [comment]
@danielgindi Could you add missing tests for several formats like `3gp` or `m4b`? If it possible for sure :)

**Comment by danielgindi** [comment]
It's kind of tough right now to find good samples

**Comment by danielgindi** [comment]
I've also separated the other mime types to single PRs

**Comment by dimapaloskin** [comment]
Cool! Thank you!

**Pull request merged**
